### ISSUE TITLE
Debug-cell still depends on backtrace 0.1

### ISSUE THREAD

**Issue by andy128k** [alexcrichton/debug-cell#1]

**Comment by alexcrichton** [comment]
Thanks for the report! I'm not sure though what's meant by this, the backtrace 0.3 crate is depended on?

**Comment by andy128k** [comment]
@alexcrichton I'm saying this [commit](https://github.com/alexcrichton/debug-cell/commit/0f07b6cc3e72d0ad77634ba77d64d84f36ac0a49) was not released to [crates.io](https://crates.io/crates/debug-cell), though it was made a year ago.

**Comment by alexcrichton** [comment]
Oops, sorry about that!
